name: Auto Merge Dependency Updates

on:
  - pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tjenkinson/gh-action-auto-merge-dependency-updates@v1
        with:
          allowed-actors: renovate[bot]
